repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint src
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]