[tool.poetry]
name = "tbd"
version = "0.1.0"
description = "tbd"
authors = ["Brandon Egger <brandonegger64@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.17.0"
watchdog = "^2.2.1"
pandas = "^1.5.3"
numpy = "^1.24.2"
pylint = "^2.16.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
