name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  BROWSER: "firefox"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #             Setup environment
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      #----------------------------------------------
      #  -----   install poetry packages    -----
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
      #----------------------------------------------
      #  -----          Run linter          -----
      #----------------------------------------------
      - name: Run PyLint
        run: |
          echo "src/:"
          poetry run pylint src
          echo "tests/:"
          poetry run pylint tests

  playwright-linux:
    needs: [lint]
    name: test-playwright
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #             Setup environment
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      #----------------------------------------------
      #  -----    install poetry packages    -----
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
      #----------------------------------------------
      #  -- install / cache playwright packages --
      #----------------------------------------------
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-${{ hashFiles('poetry.lock') }}
      
      - name: Ensure browsers are installed
        run: poetry run playwright install --with-deps
      #----------------------------------------------
      #  -----     Run PlayWright Tests     -----
      #----------------------------------------------
      - name: Run your tests
        run: poetry run python -m tests.cli --test playwright

  pyunit:
    needs: [lint]
    name: test-pyunit
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #             Setup environment
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      #----------------------------------------------
      #  -----   install poetry packages    -----
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
      #----------------------------------------------
      #  -----   install poetry packages    -----
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
      #----------------------------------------------
      #  -----       Run PyUnit Tests       -----
      #----------------------------------------------
      - name: Run your tests
        run: poetry run python -m tests.cli --test pyunit